export type Language = 'en' | 'zh';

export interface Translations {
  // Login
  loginTitle: string;
  loginSubtitle: string;
  username: string;
  password: string;
  signIn: string;
  demoHint: string;
  enterUsername: string;
  enterPassword: string;
  enterBothCredentials: string;
  invalidCredentials: string;

  // Dashboard Header
  dashboardTitle: string;
  welcome: string;
  logout: string;

  // Code List
  activationCodes: string;
  createCodes: string;
  deleteSelected: string;
  searchPlaceholder: string;
  code: string;
  status: string;
  createdAt: string;
  usedAt: string;
  userId: string;
  actions: string;
  edit: string;
  delete: string;
  noCodesMatch: string;
  noCodesYet: string;
  previous: string;
  next: string;
  pageOf: string;

  // Code Editor
  createTitle: string;
  editTitle: string;
  numberOfCodes: string;
  enterCount: string;
  codesAutoGenerated: string;
  initialStatus: string;
  activationCode: string;
  codeRequired: string;
  optional: string;
  cancel: string;
  create: string;
  createMultiple: string;
  saveChanges: string;

  // Status
  active: string;
  inactive: string;
  used: string;

  // Validation
  countRange: string;

  // Confirmations
  deleteConfirm: string;
  deleteBulkConfirm: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    // Login
    loginTitle: 'Admin Dashboard',
    loginSubtitle: 'Sign in to manage activation codes',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In',
    demoHint: 'Demo: admin / admin123',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    enterBothCredentials: 'Please enter both username and password',
    invalidCredentials: 'Invalid credentials. Try: admin / admin123',

    // Dashboard Header
    dashboardTitle: 'Activation Code Manager',
    welcome: 'Welcome',
    logout: 'Logout',

    // Code List
    activationCodes: 'Activation Codes',
    createCodes: '+ Create Codes',
    deleteSelected: 'Delete Selected',
    searchPlaceholder: 'Search by code, user ID, or status...',
    code: 'Code',
    status: 'Status',
    createdAt: 'Created At',
    usedAt: 'Used At',
    userId: 'User ID',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    noCodesMatch: 'No codes match your search',
    noCodesYet: 'No activation codes yet. Create your first one!',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page',

    // Code Editor
    createTitle: 'Create Activation Codes',
    editTitle: 'Edit Activation Code',
    numberOfCodes: 'Number of Codes to Create',
    enterCount: 'Enter count (1-10,000)',
    codesAutoGenerated: 'Codes will be auto-generated with format: ACT-YYYY-XXXXXX',
    initialStatus: 'Initial Status',
    activationCode: 'Activation Code',
    codeRequired: 'Code is required',
    optional: 'Optional',
    cancel: 'Cancel',
    create: 'Create',
    createMultiple: 'Code',
    saveChanges: 'Save Changes',

    // Status
    active: 'Active',
    inactive: 'Inactive',
    used: 'Used',

    // Validation
    countRange: 'Count must be between 1 and 10,000',

    // Confirmations
    deleteConfirm: 'Are you sure you want to delete this activation code?',
    deleteBulkConfirm: 'Delete {count} selected codes?',
  },

  zh: {
    // Login
    loginTitle: '管理员控制台',
    loginSubtitle: '登录以管理激活码',
    username: '用户名',
    password: '密码',
    signIn: '登录',
    demoHint: '演示账号：admin / admin123',
    enterUsername: '请输入用户名',
    enterPassword: '请输入密码',
    enterBothCredentials: '请输入用户名和密码',
    invalidCredentials: '凭据无效。请尝试：admin / admin123',

    // Dashboard Header
    dashboardTitle: '激活码管理系统',
    welcome: '欢迎',
    logout: '退出登录',

    // Code List
    activationCodes: '激活码',
    createCodes: '+ 创建激活码',
    deleteSelected: '删除选中项',
    searchPlaceholder: '按激活码、用户ID或状态搜索...',
    code: '激活码',
    status: '状态',
    createdAt: '创建时间',
    usedAt: '使用时间',
    userId: '用户ID',
    actions: '操作',
    edit: '编辑',
    delete: '删除',
    noCodesMatch: '没有匹配的激活码',
    noCodesYet: '还没有激活码，创建第一个吧！',
    previous: '上一页',
    next: '下一页',
    pageOf: '第',

    // Code Editor
    createTitle: '创建激活码',
    editTitle: '编辑激活码',
    numberOfCodes: '创建数量',
    enterCount: '输入数量（1-10,000）',
    codesAutoGenerated: '激活码将自动生成，格式：ACT-YYYY-XXXXXX',
    initialStatus: '初始状态',
    activationCode: '激活码',
    codeRequired: '激活码为必填项',
    optional: '可选',
    cancel: '取消',
    create: '创建',
    createMultiple: '个激活码',
    saveChanges: '保存更改',

    // Status
    active: '激活',
    inactive: '未激活',
    used: '已使用',

    // Validation
    countRange: '数量必须在 1 到 10,000 之间',

    // Confirmations
    deleteConfirm: '确定要删除此激活码吗？',
    deleteBulkConfirm: '删除选中的 {count} 个激活码？',
  },
};
