import { useState } from 'react';
import { useLanguage } from '../i18n/LanguageContext';
import type { ActivationCode } from '../types';
import './CodeEditor.css';

interface CodeEditorProps {
  code: ActivationCode | null;
  isCreating: boolean;
  onSave: (code: ActivationCode, count?: number) => void;
  onCancel: () => void;
}

export default function CodeEditor({ code, isCreating, onSave, onCancel }: CodeEditorProps) {
  const { t } = useLanguage();
  const [formData, setFormData] = useState<ActivationCode>(
    code || {
      id: '',
      code: '',
      status: 'active',
      createdAt: new Date().toISOString(),
    }
  );
  const [bulkCount, setBulkCount] = useState(1);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleChange = (field: keyof ActivationCode, value: string) => {
    setFormData({ ...formData, [field]: value });
    if (errors[field]) {
      setErrors({ ...errors, [field]: '' });
    }
  };

  const validate = () => {
    const newErrors: Record<string, string> = {};

    if (isCreating) {
      if (bulkCount < 1 || bulkCount > 10000) {
        newErrors.bulkCount = t.countRange;
      }
    } else {
      if (!formData.code.trim()) {
        newErrors.code = t.codeRequired;
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (validate()) {
      onSave(formData, isCreating ? bulkCount : undefined);
    }
  };

  return (
    <div className="code-editor">
      <div className="editor-header">
        <h2>{isCreating ? t.createTitle : t.editTitle}</h2>
      </div>

      <form onSubmit={handleSubmit} className="editor-form">
        {isCreating ? (
          <>
            <div className="form-field">
              <label htmlFor="bulkCount">{t.numberOfCodes} *</label>
              <input
                id="bulkCount"
                type="number"
                min="1"
                max="10000"
                value={bulkCount}
                onChange={e => setBulkCount(parseInt(e.target.value) || 1)}
                placeholder={t.enterCount}
                className={errors.bulkCount ? 'error' : ''}
              />
              {errors.bulkCount && <span className="field-error">{errors.bulkCount}</span>}
              <span className="field-hint">{t.codesAutoGenerated}</span>
            </div>

            <div className="form-field">
              <label htmlFor="status">{t.initialStatus}</label>
              <select
                id="status"
                value={formData.status}
                onChange={e => handleChange('status', e.target.value as ActivationCode['status'])}
              >
                <option value="active">{t.active}</option>
                <option value="inactive">{t.inactive}</option>
              </select>
            </div>
          </>
        ) : (
          <>
            <div className="form-row">
              <div className="form-field">
                <label htmlFor="code">{t.activationCode} *</label>
                <input
                  id="code"
                  type="text"
                  value={formData.code}
                  onChange={e => handleChange('code', e.target.value)}
                  placeholder="e.g., ACT-2024-001"
                  className={errors.code ? 'error' : ''}
                />
                {errors.code && <span className="field-error">{errors.code}</span>}
              </div>

              <div className="form-field">
                <label htmlFor="status">{t.status}</label>
                <select
                  id="status"
                  value={formData.status}
                  onChange={e => handleChange('status', e.target.value as ActivationCode['status'])}
                >
                  <option value="active">{t.active}</option>
                  <option value="inactive">{t.inactive}</option>
                  <option value="used">{t.used}</option>
                </select>
              </div>
            </div>

            <div className="form-row">
              <div className="form-field">
                <label htmlFor="userId">{t.userId}</label>
                <input
                  id="userId"
                  type="text"
                  value={formData.userId || ''}
                  onChange={e => handleChange('userId', e.target.value)}
                  placeholder={t.optional}
                />
              </div>

              <div className="form-field">
                <label htmlFor="usedAt">{t.usedAt}</label>
                <input
                  id="usedAt"
                  type="datetime-local"
                  value={formData.usedAt ? new Date(formData.usedAt).toISOString().slice(0, 16) : ''}
                  onChange={e =>
                    handleChange('usedAt', e.target.value ? new Date(e.target.value).toISOString() : '')
                  }
                />
              </div>
            </div>
          </>
        )}

        <div className="form-actions">
          <button type="button" onClick={onCancel} className="cancel-button">
            {t.cancel}
          </button>
          <button type="submit" className="save-button">
            {isCreating
              ? `${t.create} ${bulkCount} ${t.createMultiple}${bulkCount > 1 ? 's' : ''}`
              : t.saveChanges}
          </button>
        </div>
      </form>
    </div>
  );
}
